docker

diff --git a/docker/php-fpm/Dockerfile b/docker/php-fpm/Dockerfile
--- a/docker/php-fpm/Dockerfile
+++ b/docker/php-fpm/Dockerfile
@@ -1,175 +1,140 @@
-########################
-### Stage - "base"
-########################
-FROM php:7.4.2-fpm as dev
+FROM php:7.4.2-fpm
 
-RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
-    apt-transport-https \
-    ca-certificates \
-    openssh-client \
-    curl \
-    dos2unix \
-    git \
-    gnupg2 \
-    dirmngr \
-    g++ \
-    jq \
-    libedit-dev \
-    libfcgi0ldbl \
-    libfreetype6-dev \
-    libicu-dev \
-    libjpeg62-turbo-dev \
-    libmcrypt-dev \
-    libpq-dev \
-    supervisor \
-    unzip \
-    libssl-dev \
-    zip \
-    && rm -r /var/lib/apt/lists/*
+# always run apt update when start and after add new source list, then clean up at end.
+RUN set -xe; \
+    apt-get update -yqq && \
+    pecl channel-update pecl.php.net && \
+    apt-get install -yqq \
+      apt-utils \
+      #
+      #--------------------------------------------------------------------------
+      # Mandatory Software's Installation
+      #--------------------------------------------------------------------------
+      #
+      # Mandatory Software's such as ("mcrypt", "pdo_mysql", "libssl-dev", ....)
+      # are installed on the base image 'laradock/php-fpm' image. If you want
+      # to add more Software's or remove existing one, you need to edit the
+      # base image (https://github.com/Laradock/php-fpm).
+      #
+      # next lines are here becase there is no auto build on dockerhub see https://github.com/laradock/laradock/pull/1903#issuecomment-463142846
+      libzip-dev zip unzip && \
+      docker-php-ext-configure zip && \
+      # Install the zip extension
+      docker-php-ext-install zip && \
+      php -m | grep -q 'zip'
 
-RUN docker-php-ext-install \
-    pdo_mysql \
-    mysqli \
-    json \
-    readline \
-    gd \
-    intl \
-    pdo \
-    pdo_pgsql \
-    pgsql \
-    bcmath \
-    sockets
+###########################################################################
+# bcmath:
+###########################################################################
 
-# install mongodb ext
-#RUN pecl install mongodb \
-#    && docker-php-ext-enable mongodb
+ARG INSTALL_BCMATH=false
 
-# configure packages
-#RUN docker-php-ext-configure intl
-#RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
+RUN if [ ${INSTALL_BCMATH} = true ]; then \
+    # Install the bcmath extension
+    docker-php-ext-install bcmath \
+;fi
 
-ENV TZ=Europe/Oslo
-RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
+###########################################################################
+# Opcache:
+###########################################################################
 
-WORKDIR /var/www/back
+ARG INSTALL_OPCACHE=false
 
-# Composer
-ENV COMPOSER_ALLOW_SUPERUSER 1
-ENV COMPOSER_HOME /tmp
-ENV COMPOSER_VERSION 1.9.1
+RUN if [ ${INSTALL_OPCACHE} = true ]; then \
+    docker-php-ext-install opcache \
+;fi
 
-RUN set -eux; \
-  curl --silent --fail --location --retry 3 --output /tmp/installer.php --url https://raw.githubusercontent.com/composer/getcomposer.org/cb19f2aa3aeaa2006c0cd69a7ef011eb31463067/web/installer; \
-  php -r " \
-    \$signature = '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5'; \
-    \$hash = hash('sha384', file_get_contents('/tmp/installer.php')); \
-    if (!hash_equals(\$signature, \$hash)) { \
-      unlink('/tmp/installer.php'); \
-      echo 'Integrity check failed, installer is either corrupt or worse.' . PHP_EOL; \
-      exit(1); \
-    }"; \
-  php /tmp/installer.php --no-ansi --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION}; \
-  composer --ansi --version --no-interaction; \
-  rm -f /tmp/installer.php; \
-  find /tmp -type d -exec chmod -v 1777 {} +
+# Copy opcache configration
+COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini
 
-# Laravel App Config
-# setup app config environment at runtime
-# gets put into ./.env at startup
-ENV TZ=Europe/Kiev \
-    APP_NAME=Temabok \
-    APP_ENV=local \
-    APP_DEBUG=true \
-    APP_URL=http://localhost \
-    APP_TIMEZONE=Europe/Kiev \
+###########################################################################
+# Mysqli Modifications:
+###########################################################################
 
-    LOG_CHANNEL=stack \
+ARG INSTALL_MYSQLI=false
 
-    DB_CONNECTION=mysql \
-    DB_HOST=mysql \
-    DB_PORT=3306 \
+RUN if [ ${INSTALL_MYSQLI} = true ]; then \
+    docker-php-ext-install mysqli \
+;fi
 
-#    DB_CONNECTION=pgsql \
-#    DB_HOST_MANAGEMENT=postgres \
-#    DB_PORT_MANAGEMENT=5432 \
+
+###########################################################################
+# Human Language and Character Encoding Support:
+###########################################################################
+
+ARG INSTALL_INTL=false
+
+RUN if [ ${INSTALL_INTL} = true ]; then \
+    # Install intl and requirements
+    apt-get -y update && \
+    apt-get install -y zlib1g-dev libicu-dev g++ && \
+    docker-php-ext-configure intl && \
+    docker-php-ext-install intl \
+;fi
+
+###########################################################################
+# ImageMagick:
+###########################################################################
+
+USER root
+
+ARG INSTALL_IMAGEMAGICK=false
+
+RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
+    apt-get install -y libmagickwand-dev imagemagick && \
+    pecl install imagick && \
+    docker-php-ext-enable imagick \
+;fi
+
+
+###########################################################################
+# PHP REDIS EXTENSION
+###########################################################################
+
+ARG INSTALL_PHPREDIS=false
+
+RUN if [ ${INSTALL_PHPREDIS} = true ]; then \
+    # Install Php Redis Extension
+    if [ $(php -r "echo PHP_MAJOR_VERSION;") = "5" ]; then \
+      pecl install -o -f redis-4.3.0; \
+    else \
+      pecl install -o -f redis; \
+    fi \
+    && rm -rf /tmp/pear \
+    && docker-php-ext-enable redis \
+;fi
+
 #
-#    DB_CONNECTION_DRAFT=mongodb \
-#    DB_HOST_DRAFT=mongo \
-#    DB_PORT_DRAFT=27017 \
-
-    FILESYSTEM_DRIVER=public_uploads \
-
-    BROADCAST_DRIVER=log \
-    CACHE_DRIVER=file \
-    QUEUE_CONNECTION=sync \
-    SESSION_DRIVER=file \
-    SESSION_LIFETIME=120 \
-
-    REDIS_HOST=127.0.0.1 \
-    REDIS_PASSWORD=null \
-    REDIS_PORT=6379 \
-
-    MAIL_DRIVER=smtp \
-    MAIL_HOST=smtp.mailtrap.io \
-    MAIL_PORT=2525 \
-    MAIL_USERNAME=null \
-    MAIL_PASSWORD=null \
-    MAIL_ENCRYPTION=null \
-
-    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}" \
-    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
-# Many more ENV may be needed here, and updated in docker-php-entrypoint file
-
-#COPY devops/php/wait-for-it.sh /usr/local/bin/wait-for-it.sh
-#RUN chmod +x /usr/local/bin/wait-for-it.sh
-
-# Boot.sh
-COPY docker/boot.sh /usr/local/bin/php_boot.sh
-RUN chmod +x /usr/local/bin/php_boot.sh
-
-#CMD /usr/local/bin/wait-for-it.sh postgres:5432 -- /usr/local/bin/wait-for-it.sh mongo:27017 -- /usr/local/bin/php_boot.sh
-
-
-
-########################
-### Stage - "development"
-########################
-FROM base as test
-
-RUN apt-get update && apt-get install -y wget git unzip \
-    && pecl install xdebug \
-    && docker-php-ext-enable xdebug
-
-COPY ./docker/php-fpm/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
-
-
-
-########################
-### Stage - "test"
-########################
-FROM base as test
-
-#WORKDIR /var/www/back
+#--------------------------------------------------------------------------
+# Final Touch
+#--------------------------------------------------------------------------
 #
-#COPY devops/php/boot.test.sh /usr/local/bin/php_boot.sh
-#RUN chmod +x /usr/local/bin/php_boot.sh
-#
-#COPY . .
-#
-#RUN chown -R :www-data storage bootstrap/cache
-#RUN chmod -R g+w storage bootstrap/cache
-#
-#RUN composer install --no-scripts --no-autoloader --ansi --no-interaction -d /var/www/back
-#RUN composer dump-autoload -d /var/www/back
-#
-#CMD /usr/local/bin/wait-for-it.sh postgres:5432 -- /usr/local/bin/wait-for-it.sh mongo:27017 -- /usr/local/bin/php_boot.sh
 
+COPY ./laravel.ini /usr/local/etc/php/conf.d
+COPY ./xlaravel.pool.conf /usr/local/etc/php-fpm.d/
 
+USER root
 
-########################
-### Stage - "production"
-########################
-#FROM base as prod
-#
-#COPY --chown=www-data:www-data .. /var/www/back
-#RUN /usr/local/bin/composer.phar dump-autoload -o
+# Clean up
+RUN apt-get clean && \
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
+    rm /var/log/lastlog /var/log/faillog
+
+# Configure non-root user.
+ARG PUID=1000
+ENV PUID ${PUID}
+ARG PGID=1000
+ENV PGID ${PGID}
+
+RUN groupmod -o -g ${PGID} www-data && \
+    usermod -o -u ${PUID} -g www-data www-data
+
+# Configure locale.
+ARG LOCALE=POSIX
+ENV LC_ALL ${LOCALE}
+
+WORKDIR /var/www/html/
+
+CMD ["php-fpm"]
+
+EXPOSE 9000
